---
title: "easyclimate: easy access to high-resolution daily climate data for Europe"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{easyclimate: easy access to high-resolution daily climate data for Europe}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(easyclimate)
```

## Examples

```{r}
# Coords as matrix
coords <- matrix(c(-5.36, 37.40), ncol = 2)

ex <- get_daily_climate(coords, period = "2001-01-01")  # single day
ex

ex <- get_daily_climate(coords, period = c("2001-01-01", "2001-01-03"))  # 1st AND 3rd Jan 2001
ex

ex <- get_daily_climate(coords, period = "2001-01-01:2001-01-03")  # 1st TO 3rd Jan 2001
ex

ex <- get_daily_climate(coords, period = 2008)  # entire year
head(ex)
tail(ex)

ex <- get_daily_climate(coords, period = c(2008, 2010))  # 2008 AND 2010
head(ex)
tail(ex)

ex <- get_daily_climate(coords, period = 2008:2010)  # 2008 TO 2010
head(ex)
tail(ex)

## Differnet climatic_var
ex <- get_daily_climate(coords, period = "2001-01-01", climatic_var = "Tmin")


# Coords as data.frame
coords <- as.data.frame(coords)
names(coords) <- c("lon", "lat")  # must have these columns
ex <- get_daily_climate(coords, period = "2001-01-01")  # single day
ex

# Coords as sf
coords <- sf::st_as_sf(coords, coords = c("lon", "lat"))
ex <- get_daily_climate(coords, period = "2001-01-01")  # single day
ex

# Several points
coords <- matrix(c(-5.36, 37.40, -4.05, 38.10), ncol = 2, byrow = TRUE)
ex <- get_daily_climate(coords, period = "2001-01-01")
ex

ex <- get_daily_climate(coords, period = "2001-01-01", output = "raster")  # raster output
ex
library(terra)
plot(ex)


## Polygons
coords <- terra::vect("POLYGON ((-5 38, -5 37.5, -4.5 37.5, -4.5 38, -5 38))")

# Return raster
ex <- get_daily_climate(coords, period = "2001-01-01", output = "raster")
ex
plot(ex)

# Calculate average across polygon
ex <- get_daily_climate(coords, period = "2001-01-01", fun = "mean")
ex
# Calculate min across polygon
ex <- get_daily_climate(coords, period = "2008-09-27", fun = "min")
ex
```


## Calculating monthly, yearly and other indices


## Examples: evolution of tmean in January for a site, multilayer rasters, etc
